<?php

declare(strict_types=1);

namespace Database\Seeders;

use App\Enums\SystemRole;
use Illuminate\Database\Seeder;
use Spatie\Permission\Models\Permission;
use Spatie\Permission\Models\Role;
use Spatie\Permission\PermissionRegistrar;

class RolesAndPermissionsSeeder extends Seeder
{
    /**
     * @return array<int, string>
     */
    public static function permissions(): array
    {
        return array_values(array_unique([
            'dashboard.view',
            'users.view',
            'users.create',
            'users.update',
            'users.ban',
            'users.delete',
            'roles.manage',
            'departments.view',
            'departments.manage',
            'branches.view',
            'branches.create',
            'branches.update',
            'branches.delete',
            'teams.view',
            'teams.manage',
            'advisory-categories.view',
            'advisory-categories.manage',
            'complaint-categories.view',
            'complaint-categories.manage',
            'courts.view',
            'courts.manage',
            'legal-case-types.view',
            'legal-case-types.manage',
            'letter_templates.view',
            'letter_templates.create',
            'letter_templates.update',
            'letter_templates.delete',
            'letter_templates.preview',
            'letter_templates.print',
            'letters.view',
            'letters.create',
            'letters.update',
            'letters.delete',
            'letters.preview',
            'letters.print',
            'letters.approve',
            'advisory-requests.view',
            'advisory-requests.create',
            'advisory-requests.review',
            'advisory-requests.assign',
            'advisory-requests.respond',
            'advisory-requests.close',
            'advisory-responses.comment',
            'advisory-responses.approve',
            'legal-cases.view',
            'legal-cases.create',
            'legal-cases.review',
            'legal-cases.assign',
            'legal-cases.update',
            'legal-cases.close',
            'attachments.view',
            'attachments.create',
            'attachments.delete',
            'comments.view',
            'comments.create',
            'reports.view',
            'audit-logs.view',
            'settings.manage',
            'public-posts.view',
            'public-posts.manage',
            'reports.export',
            'users.assign_roles',
            'references.view',
            'references.manage',
            'advisory.view_any',
            'advisory.view_own',
            'advisory.create',
            'advisory.submit',
            'advisory.review',
            'advisory.assign_team_leader',
            'advisory.assign_expert',
            'advisory.respond',
            'advisory.comment',
            'advisory.attach',
            'advisory.export',
            'cases.view_any',
            'cases.view_own',
            'cases.create',
            'cases.review',
            'cases.assign_team_leader',
            'cases.assign_expert',
            'cases.record_hearing',
            'cases.close',
            'cases.reopen',
            'case-reopen',
            'cases.comment',
            'cases.attach',
            'cases.export',
            'audit.view',
            'complaints.view',
            'complaints.create',
            'complaints.view_own',
            'complaints.view_department',
            'complaints.respond_department',
            'complaints.forward_to_committee',
            'complaints.committee.review',
            'complaints.committee.decide',
            'complaints.settings.manage',
            'complaints.reports.view',
            'complaints.view_all',
            'complaints.attachments.manage',
            'lawsuit-requests.view',
            'lawsuit-requests.create',
            'lawsuit-requests.update',
            'lawsuit-requests.review',
            'lawsuit-requests.approve',
            'lawsuit-requests.reject',
            'lawsuit-requests.delete',
        ]));
    }

    public function run(): void
    {
        app(PermissionRegistrar::class)->forgetCachedPermissions();

        /** @var array<string, array{en: string, am: string}> $descriptions */
        $descriptions = config('permission_descriptions', []);

        foreach (self::permissions() as $permission) {
            $record = Permission::query()->firstOrNew([
                'name' => $permission,
                'guard_name' => 'web',
            ]);

            $record->forceFill([
                'description_en' => filled($record->description_en) ? $record->description_en : ($descriptions[$permission]['en'] ?? null),
                'description_am' => filled($record->description_am) ? $record->description_am : ($descriptions[$permission]['am'] ?? null),
            ]);

            $record->save();
        }

        foreach (self::rolePermissions() as $roleName => $permissions) {
            $role = Role::findOrCreate($roleName, 'web');
            $role->syncPermissions(array_values(array_unique($permissions)));
        }
    }

    /**
     * @return array<string, array<int, string>>
     */
    public static function rolePermissions(): array
    {
        return [
            SystemRole::SUPER_ADMIN->value => self::permissions(),
            SystemRole::LEGAL_DIRECTOR->value => [
                'dashboard.view',
                'departments.view',
                'teams.view',
                'advisory-categories.view',
                'complaint-categories.view',
                'courts.view',
                'legal-case-types.view',
                'letter_templates.view',
                'letter_templates.preview',
                'letter_templates.print',
                'letters.view',
                'letters.create',
                'letters.update',
                'letters.preview',
                'letters.print',
                'letters.approve',
                'advisory-requests.view',
                'advisory-requests.review',
                'advisory-requests.assign',
                'advisory-requests.close',
                'advisory-responses.comment',
                'advisory-responses.approve',
                'legal-cases.view',
                'legal-cases.review',
                'legal-cases.assign',
                'legal-cases.update',
                'legal-cases.close',
                'attachments.view',
                'comments.view',
                'reports.view',
                'audit-logs.view',
                'public-posts.view',
                'public-posts.manage',
                'reports.export',
                'references.view',
                'advisory.view_any',
                'advisory.review',
                'advisory.assign_team_leader',
                'advisory.comment',
                'advisory.attach',
                'cases.view_any',
                'cases.review',
                'cases.assign_team_leader',
                'cases.comment',
                'cases.attach',
                'complaints.view',
                'complaints.view_all',
                'complaints.view_department',
                'complaints.respond_department',
                'complaints.committee.review',
                'complaints.committee.decide',
                'complaints.settings.manage',
                'complaints.reports.view',
                'complaints.attachments.manage',
                'audit.view',
                'public-posts.view',
                'public-posts.manage',
                'lawsuit-requests.view',
                'lawsuit-requests.review',
                'lawsuit-requests.approve',
                'lawsuit-requests.reject',
            ],
            SystemRole::LITIGATION_TEAM_LEADER->value => [
                'dashboard.view',
                'legal-cases.view',
                'legal-cases.assign',
                'legal-cases.update',
                'legal-cases.close',
                'attachments.view',
                'attachments.create',
                'comments.view',
                'comments.create',
                'cases.view_any',
                'cases.assign_expert',
                'cases.record_hearing',
                'cases.close',
                'cases.comment',
                'cases.attach',
                'complaints.view',
                'complaints.view_department',
                'complaints.respond_department',
                'complaints.attachments.manage',
                'lawsuit-requests.view',
            ],
            SystemRole::ADVISORY_TEAM_LEADER->value => [
                'dashboard.view',
                'advisory-requests.view',
                'advisory-requests.assign',
                'advisory-requests.respond',
                'advisory-responses.comment',
                'attachments.view',
                'attachments.create',
                'comments.view',
                'comments.create',
                'advisory.view_any',
                'advisory.assign_expert',
                'advisory.comment',
                'advisory.attach',
                'complaints.view',
                'complaints.view_department',
                'complaints.respond_department',
                'complaints.attachments.manage',
            ],
            SystemRole::LEGAL_EXPERT->value => [
                'dashboard.view',
                'advisory-requests.view',
                'advisory-requests.respond',
                'advisory-responses.comment',
                'legal-cases.view',
                'legal-cases.update',
                'attachments.view',
                'attachments.create',
                'comments.view',
                'comments.create',
                'advisory.view_any',
                'advisory.respond',
                'advisory.comment',
                'advisory.attach',
                'cases.view_any',
                'cases.record_hearing',
                'cases.comment',
                'cases.attach',
                'complaints.view',
                'complaints.view_department',
                'complaints.respond_department',
                'complaints.attachments.manage',
                'lawsuit-requests.view',
            ],
            SystemRole::DEPARTMENT_REQUESTER->value => [
                'dashboard.view',
                'advisory-requests.view',
                'advisory-requests.create',
                'attachments.view',
                'attachments.create',
                'comments.view',
                'comments.create',
                'advisory.view_own',
                'advisory.create',
                'advisory.submit',
                'advisory.comment',
                'advisory.attach',
                'complaints.view',
                'complaints.create',
                'complaints.view_own',
                'complaints.forward_to_committee',
                'complaints.attachments.manage',
                'lawsuit-requests.view',
                'lawsuit-requests.create',
            ],
            SystemRole::REGISTRAR->value => [
                'dashboard.view',
                'legal-cases.view',
                'legal-cases.create',
                'attachments.view',
                'attachments.create',
                'comments.view',
                'comments.create',
                'cases.view_any',
                'cases.create',
                'cases.comment',
                'cases.attach',
                'complaints.view',
                'complaints.view_department',
                'complaints.respond_department',
                'complaints.attachments.manage',
            ],
            SystemRole::AUDITOR->value => [
                'dashboard.view',
                'advisory-requests.view',
                'legal-cases.view',
                'attachments.view',
                'comments.view',
                'reports.view',
                'audit-logs.view',
                'advisory.view_any',
                'cases.view_any',
                'complaints.view',
                'complaints.view_all',
                'complaints.reports.view',
                'audit.view',
                'lawsuit-requests.view',
            ],
            SystemRole::COMPLAINT_COMMITTEE->value => [
                'dashboard.view',
                'attachments.view',
                'attachments.create',
                'attachments.delete',
                'complaints.view',
                'complaints.committee.review',
                'complaints.committee.decide',
                'complaints.reports.view',
            ],
            SystemRole::COMPLAINT_CLIENT->value => [
                'dashboard.view',
                'attachments.view',
                'attachments.create',
                'complaints.view',
                'complaints.create',
                'complaints.view_own',
                'complaints.forward_to_committee',
            ],
        ];
    }
}
